#spring.application.name=employee
#
#spring.datasource.url=jdbc:mysql://localhost:3306/employee_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=3rickP4dilla$
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#
#server.port=8080
#
#logging.level.root=INFO
#logging.level.com.bpadilla.employee=DEBUG

spring.application.name=employee

spring.datasource.url=jdbc:mysql://mysql-db:3306/employee_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=appuser
spring.datasource.password=app123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
spring.datasource.hikari.initializationFailTimeout=60000
spring.datasource.hikari.connectionTimeout=30000

server.port=8080

logging.level.root=INFO
logging.level.com.bpadilla.employee=DEBUG